/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import Image from "next/image";
import "./globals.css"
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
        <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@700&family=Poppins:wght@700&family=Roboto:wght@700&display=swap" rel="stylesheet"/>

      </head>
      <body>
        <header>
          <a href="#">
          <Image
            src={"/logo_site.png"}
            alt="Logo Site"
            priority
            width={226}
            height={95}
          />
          </a>

          <form action="" className="form-header">
            <div className="search-bar">
              <input type="text" className="input-search" placeholder="Pesquise sua dúvida"/>
              <button type="submit" className="button-search"><i className="fa-solid fa-magnifying-glass"></i></button>
            </div>
          </form>

          <nav>
            <button type="button" className="button-enter" >Login</button>
            <button type="button" className="button-enter" >Cadastro</button>
            <button type="button" className="button-profile"><i className="fa-solid fa-user"></i></button>
            
          </nav>

        </header>
        {children}
        <Script
        src="https://kit.fontawesome.com/a12b6f56b1.js"
        strategy="afterInteractive"
        crossOrigin="anonymous"
        />
      </body>
    </html>
  );
}
